# 오직 도메인 연결을 위한 프록시 구성이므로 기본 구성은 docker-compose.aws.yml 그대로 사용
# .evnv의 FE_HOST, BE_HOST 값만 사용할 도메인으로 변경하면 됨
include:
- docker-compose.aws.yml



services:
  # ----------------------------------------------------------------------------
  # 1. PROXY SERVICES (프록시 서버, 도메인별 다른 컨테이너로 연결 및 HTTPS 자동 적용하기 위한 용도)
  # ----------------------------------------------------------------------------

  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.12-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy:/data



  # ----------------------------------------------------------------------------
  # 2. CONNECTED DOMAINS (도메인별로 연결할 실제 서비스 컨테이너)
  # ----------------------------------------------------------------------------

  lifemap-backend:
    labels:
      caddy: ${BE_HOST}
      caddy.reverse_proxy: "{{upstreams 8000}}"

  lifemap-frontend:
    environment:
      VITE_BACKEND_URL: https://${BE_HOST}
    labels:
      caddy: ${FE_HOST}
      caddy.reverse_proxy: "{{upstreams 3000}}"

volumes:
  caddy:
