# 공통 헬스체크 설정 템플릿 (앵커로 사용)
x-health-check-times: &healthcheck_times
  interval: 5s
  timeout: 5s
  retries: 5
  start_period: 15s



services:
  # ----------------------------------------------------------------------------
  # 1. CACHE & MONITORING SERVICES (캐시 서버)
  # ----------------------------------------------------------------------------

  # Redis 서버
  redis:
    container_name: overclock-redis
    image: redis:8.6
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck_times
      test:
        - CMD
        - redis-cli
        - ping
    volumes:
      - redis-data:/data
    environment:
      TZ: ${TZ}

  # Redis 모니터링 및 관리 도구 (웹 GUI)
  redis-ui:
    profiles:
      - redis-ui
    container_name: overclock-redis-ui
    image: redis/redisinsight:3.4
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
        required: true
    ports:
      - "${REDIS_UI_PORT:-5540}:5540"
    volumes:
      - redisinsight-data:/data
    environment:
      TZ: ${TZ}
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379



  # ----------------------------------------------------------------------------
  # 2. DATABASE SERVICES (데이터베이스 서버)
  # ----------------------------------------------------------------------------

  # MariaDB 데이터베이스 서버
  database:
    profiles:
      - database
    image: lscr.io/linuxserver/mariadb:latest
    container_name: overclock-database
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck_times
      test:
        - CMD
        - mariadb-admin
        - ping
        - -h
        - localhost
    ports:
      - "127.0.0.1:${DB_EXTERNAL_PORT:-3306}:3306"
    volumes:
      - mariadb-data:/config
    environment:
      TZ: ${TZ}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}



  # ----------------------------------------------------------------------------
  # 3. SERVICES (서버 구성)
  # ----------------------------------------------------------------------------

  # 백엔드 (FastAPI)
  backend:
    image: ghcr.io/team-overclock/backend:latest
    container_name: overclock-backend
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
        required: true
      database:
        condition: service_healthy
        required: false
    ports:
      - "${BE_PORT:-8000}:8000"
    volumes:
      - ./backend-data:/app/data
    environment:
      TZ: ${TZ}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      MODE: development  # hot reload, swagger/scalar 사용하려면 development로 변경
      PROTO: ${BE_PROTO}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER:
      REDIS_PASS:
      REDIS_DB: 0
      GUEST_LOGIN_ENABLE: ${GUEST_LOGIN_ENABLE:-false}
      GUEST_USERNAME: ${GUEST_USERNAME:-}
      GUEST_EMAIL: ${GUEST_EMAIL:-}
      GUEST_PASSWORD: ${GUEST_PASSWORD:-}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: localhost,127.0.0.1,${BE_HOST}
      TRUSTED_HOSTS: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.1

  # 운영 환경 프론트엔드 (React / Vite)
  frontend:
    image: ghcr.io/team-overclock/frontend:latest
    container_name: overclock-frontend
    restart: unless-stopped
    ports: 
    - "${FE_PORT:-3000}:3000"
    environment:
      TZ: ${TZ}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      VITE_BACKEND_URL: ${BE_PROTO}://${BE_HOST}:${BE_PORT}
      VITE_KAKAO_MAP_API_KEY: ${KAKAO_MAP_API_KEY}



# 볼륨 정의
volumes:
  redis-data:
  redisinsight-data:
  mariadb-data:
