x-health-check-times: &healthcheck_times
  interval: 5s
  timeout: 5s
  retries: 5
  start_period: 15s



services:
  # redis 캐시 서버
  overclock-redis:
    profiles:
      - redis
    container_name: overclock-redis
    image: redis:8.6
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck_times
      test:
        - CMD
        - redis-cli
        - ping
    volumes:
      - ./redis/data:/data
    environment:
      - TZ=${TZ}

  # redis 모니터링 및 관리 도구
  overclock-redisinsight:
    container_name: overclock-redisinsight
    image: redis/redisinsight:3.4
    restart: unless-stopped
    depends_on:
      - overclock-redis
    ports:
      - 5540:5540
    volumes:
      - ./redis/insight:/data
    environment:
      - TZ=${TZ}
      - RI_REDIS_HOST=${REDIS_HOST:-overclock-redis}
      - RI_REDIS_PORT=${REDIS_PORT:-6379}
      - RI_REDIS_USERNAME=${REDIS_USER:-}
      - RI_REDIS_PASSWORD=${REDIS_PASS:-}

  # 데이터베이스 서버
  overclock-database:
    profiles:
      - database
    image: lscr.io/linuxserver/mariadb:latest
    container_name: overclock-database
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck_times
      test:
        - CMD
        - mariadb-admin
        - ping
        - -h
        - localhost
    ports:
      - "3306:3306"
    environment:
      - TZ=${TZ}
      - PUID=${PUID:-1000}
      - PGID=${PUID:-1000}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - ./database:/config



  # 운영용 서버 구성

  overclock-backend-prod:
    profiles:
      - prod
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    image: overclock-backend-prod
    container_name: overclock-backend-prod
    restart: unless-stopped
    depends_on: &be_depends_on
      overclock-redis:
        condition: service_healthy
        required: false
      overclock-database:
        condition: service_healthy
        required: false
    ports:
      - "${BE_PORT:-8000}:8000"
    environment: &be_env
      - TZ=${TZ}
      - PUID=${PUID:-1000}
      - PGID=${PUID:-1000}
      - DB_HOST=${DB_HOST:-overclock-database}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=${REDIS_HOST:-overclock-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USER=${REDIS_USER:-}
      - REDIS_PASS=${REDIS_PASS:-}
      - REDIS_DB=${REDIS_DB:-0}
      - GUEST_LOGIN_ENABLE=${GUEST_LOGIN_ENABLE}
      - GUEST_USERNAME=${GUEST_USERNAME}
      - GUEST_EMAIL=${GUEST_EMAIL}
      - GUEST_PASSWORD=${GUEST_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}

  overclock-frontend-prod:
    profiles:
      - prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      args:
        - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
        - VITE_KAKAO_MAP_API_KEY=${KAKAO_MAP_API_KEY}
    image: overclock-frontend-prod
    container_name: overclock-frontend-prod
    restart: unless-stopped
    ports:
      - "${FE_PORT:-3000}:3000"
    environment:
      - TZ=${TZ}
      - PUID=${PUID:-1000}
      - PGID=${PUID:-1000}



  # 개발용 서버 구성

  overclock-backend-dev:
    profiles:
      - dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    image: overclock-backend-dev
    container_name: overclock-backend-dev
    restart: unless-stopped
    depends_on: *be_depends_on
    ports:
      - "${BE_PORT:-8000}:8000"
    volumes:
      - ./backend:/app:ro
      - venv:/venv
    environment: *be_env

  overclock-frontend-dev:
    profiles:
      - dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    image: overclock-frontend-dev
    container_name: overclock-frontend-dev
    restart: unless-stopped
    ports:
      - "${FE_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app:ro
      - node_modules:/app/node_modules
    environment:
      - TZ=${TZ}
      - PUID=${PUID:-1000}
      - PGID=${PUID:-1000}
      - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
      - VITE_KAKAO_MAP_API_KEY=${KAKAO_MAP_API_KEY}

volumes:
  venv:
  node_modules:
